### ISSUE TITLE
Getting Started For Contributors

### ISSUE THREAD

**Issue by wtrocki** [aerogear/datasync#106]
## Motivation

Our documentation contains lots of useful information about contributing but since we use couple different repositories, we gathered required information in one place, till we get them ported to AeroGear website over time.

## Introduction

AeroGear is set of the mobile focused services that help developers to write their mobile and backend software. For more general information about AeroGear please check our website:

http://aerogear.org

Voyager (this repository) is one of the services that are currently under active development. Voyager is a set of GraphQL extensions that help mobile developers to adapt GraphQL technology.

Early preview of documentation is available here: 
https://deploy-preview-613--aerogear-docs-preview.netlify.com/aerogear/latest/data-sync/

Please mind that this document is still incomplete and individual repositories should have much more information.

##  How I can start with  GraphQL/Voyager 

GraphQL is a data query standard that is gaining lots of attention recently over classical REST API approach.
There are numerous tutorials related to GraphQL and Apollo GraphQL.
Best way to start is to learn the basics of GraphQL
https://graphql.org/graphql-js/

Next step is to get yourself familiar with Apollo GraphQL technology. 
I personally found robinwieruch.com tutorials one of the best and most up to date resources:

For the client: 
https://www.robinwieruch.de/graphql-apollo-client-tutorial/
For the server:
https://www.robinwieruch.de/graphql-apollo-server-tutorial/

## Voyager Getting Started

Voyager is currently maintained in 3 different repositories:

Our **Example app** that contains server and client integrations for voyager and other AeroGear extensions:

 https://github.com/aerogear/ionic-showcase

**Server:**
https://github.com/aerogear/voyager-server/

**Client:** 
https://github.com/aerogear/aerogear-js-sdk/tree/master/packages/sync

Please check individual README.md files and CONTRIBUTING.md files for more information.

## Working on the tasks

To start working on one of the ideas please leave a a comment on one issue:
https://github.com/aerogear/voyager-server/issues?q=is%3Aissue+is%3Aopen+label%3Aideas

Mentors will reach out to you and explain the details of the tasks and possible steps.

## Ask us anything

If you found any information unclear feel free to ask question below. 

ping @aerogear/voyager team.

**Comment by pratiklodha** [comment]
Hello, I am Pratik currently in the final year masters program. I am skilled in backend development using Node and GraphQL. I am excited about GSoC 2020 and would like to know if there are any projects/issues which involve GraphQL and API development. I want to start contributing and would love to hear back from you.

**Comment by pratiklodha** [comment]
Hello, I am Pratik currently in the final year masters program. I am skilled in backend development using Node and GraphQL. I am excited about GSoC 2020 and would like to know if there are any projects/issues which involve GraphQL and API development. I want to start contributing and would love to hear back from you. I can also be reached at pratiklodha01@gmail.com (preferable).

**Comment by wtrocki** [comment]
Hi

We help with mentoring and can help to with finding the issue that will be the best for you. 
Please join our community chat that where we have GSOC channel to speak about the issues:

https://discord.gg/mJ7j84m

**Comment by amanbora** [comment]
Hello sir, I'm a BTech student. I'm interested in GSOC 2020 and would like to browse around the issues and ideas to contribute to.

**Comment by wtrocki** [comment]
Easy issue to grab https://github.com/aerogear/datasync/issues/257

**Comment by wtrocki** [comment]
Closing as outdated
