### ISSUE TITLE
.net core alternative ?

### ISSUE THREAD

**Issue by Hasan-git** [aerogear/datasync#177]

**Comment by wtrocki** [comment]
Ping @darahayes

**Comment by darahayes** [comment]
Hey @Hasan-git 👋 thanks for your issue! Could you maybe provide a little bit more detail? Are you looking for a .net alternative to voyager-server as a whole? Or are there specific components/features you're interested in? I have close to zero experience with the .net ecosystem so some additional info would be great.

**Comment by wtrocki** [comment]
This comes from offix so it may be exclusively for conflicts

**Comment by wtrocki** [comment]
Closing as we do not plan to support net core
