### ISSUE TITLE
Code Coverage is Low

### ISSUE THREAD

**Issue by darahayes** [aerogear/datasync#182]
The code coverage we have right now is really low. The last time I checked it was around 55% which is fairly unacceptable. There are a couple of modules (example: [metrics](https://github.com/aerogear/voyager-server/issues/58)) that are totally lacking in tests.

**Comment by Kishan-Dhakan** [comment]
@darahayes I would like to contribute to this issue. How should I start?

**Comment by wtrocki** [comment]
@Kishan-Dhakan Sorry for getting back to you so late. We recently removed some of the components. If you still wish to contribute feel free to try out one of the sample apps we have build to see if we can improve them somewhow
