### ISSUE TITLE
Custom GraphQL Scalars do not work when audit logging or metrics is enabled

### ISSUE THREAD

**Issue by darahayes** [aerogear/datasync#256]
* **Module**:
* **Version**:
* **Node.js / npm versions:**

Because of this code here: https://github.com/aerogear/datasync/blob/master/packages/voyager-server/src/VoyagerServer.ts#L21-L23

All top level resolvers are getting wrapped inside another resolver that does metrics and audit logging

This breaks custom scalars because the scalar resolver function also gets wrapped

**Comment by wtrocki** [comment]
Outdated. No audit logging present
