### ISSUE TITLE
Need to a testing strategy for metrics

### ISSUE THREAD

**Issue by darahayes** [aerogear/datasync#58]
* **Module**: apollo-voyager-metrics
* **Version**: all
* **Node.js / npm versions:** all

Right now our test coverage of apollo-voyager-metrics is really poor. We need 

* To test that things like resolver timing metrics are actually exposed
* That the middleware methods behave the way we want

**Comment by wtrocki** [comment]
The reason why this happened in the first place is that we were missing coverage reports on PR's so this was overlooked. Over the long time we should think about exposing coverage in PRs' and make build fail if it drops badly. Having this on PR will also encourage devs to write more. While writing tests as task seems to be strange it's best to just start adding them next time we will work on metrics.

Ping @aliok
